Change macos targets
The current targets throw an error because macos no longer supports proprietary gnu:


error: unable to find or provide libc for target 'aarch64-macos.13.0...15.3.1-gnu'
info: zig can provide libc for related target aarch64-macos.11.0.0-none